export interface HistoryItem {
  label: string;
  correct_zone?: string;
  is_correct: boolean;
}

export interface HistoryLevelConfig {
  id: number;
  categoryId: string;
  levelInCategory: number;
  title: string;
  question: string;
  hint?: string;
  background_image: string;
  portal_image: string;
  items: HistoryItem[];
}

// ========================================
// 🟢 BASIC — HEOGRAPIYA (Geography) - Levels 1-15
// ========================================
const basicGeography: HistoryLevelConfig[] = [
  {
    id: 1,
    categoryId: "BASIC",
    levelInCategory: 1,
    title: "Kabisera ng Pilipinas",
    question: "Ano ang kabisera ng Pilipinas?",
    hint: "Ito ang lungsod kung saan matatagpuan ang Malacañang Palace",
    background_image: "placeholder-bg",
    portal_image: "/assets/manila.jpg",
    items: [
      { label: "Maynila", correct_zone: "philippines", is_correct: true },
      { label: "Cebu", is_correct: false },
      { label: "Davao", is_correct: false },
      { label: "Baguio", is_correct: false },
    ],
  },
  {
    id: 2,
    categoryId: "BASIC",
    levelInCategory: 2,
    title: "Pinakamataas na Anyong Lupa",
    question: "Aling anyong lupa ang pinakamataas sa Pilipinas?",
    hint: "Matatagpuan ito sa karaniwang matataas na lugar",
    background_image: "placeholder-bg",
    portal_image: "/assets/bundok.jpg",
    items: [
      { label: "Bundok", correct_zone: "philippines", is_correct: true },
      { label: "Ilog", is_correct: false },
      { label: "Lawa", is_correct: false },
      { label: "Kapatagan", is_correct: false },
    ],
  },
  {
    id: 3,
    categoryId: "BASIC",
    levelInCategory: 3,
    title: "Pinakamahabang Ilog",
    question: "Ano ang pinakamahabang ilog sa Pilipinas?",
    hint: "Ito ay matatagpuan sa Northern Luzon",
    background_image: "placeholder-bg",
    portal_image: "/assets/cagayan.jpg",
    items: [
      { label: "Cagayan", correct_zone: "philippines", is_correct: true },
      { label: "Pasig", is_correct: false },
      { label: "Agusan", is_correct: false },
      { label: "Pampanga", is_correct: false },
    ],
  },
  {
    id: 4,
    categoryId: "BASIC",
    levelInCategory: 4,
    title: "Bilang ng Rehiyon",
    question: "Ilang rehiyon mayroon ang Pilipinas?",
    hint: "Ang Pilipinas ay may labinlima hanggang labinsiyam na rehiyon",
    background_image: "placeholder-bg",
    portal_image: "/assets/rehiyon.jpg",
    items: [
      { label: "17", correct_zone: "philippines", is_correct: true },
      { label: "16", is_correct: false },
      { label: "18", is_correct: false },
      { label: "19", is_correct: false },
    ],
  },
  {
    id: 5,
    categoryId: "BASIC",
    levelInCategory: 5,
    title: "Dagat sa Kanluran",
    question: "Aling dagat ang matatagpuan sa kanluran ng Luzon?",
    hint: "Ito ang dagat sa pagitan ng Pilipinas at China",
    background_image: "placeholder-bg",
    portal_image: "/assets/west-philippine-sea.png",
    items: [
      { label: "Dagat Kanlurang Pilipinas", correct_zone: "philippines", is_correct: true },
      { label: "Dagat Pasipiko", is_correct: false },
      { label: "Dagat Celebes", is_correct: false },
      { label: "Dagat Pilipinas", is_correct: false },
    ],
  },
  {
    id: 6,
    categoryId: "BASIC",
    levelInCategory: 6,
    title: "Rehiyon ng Baguio",
    question: "Aling rehiyon matatagpuan ang Baguio?",
    hint: "Ito ang rehiyon ng mga bundok sa Luzon",
    background_image: "placeholder-bg",
    portal_image: "/assets/baguio-car.png",
    items: [
      { label: "Cordillera Administrative Region", correct_zone: "philippines", is_correct: true },
      { label: "CALABARZON", is_correct: false },
      { label: "Central Luzon", is_correct: false },
      { label: "Visayas", is_correct: false },
    ],
  },
  {
    id: 7,
    categoryId: "BASIC",
    levelInCategory: 7,
    title: "Lawang Tubig",
    question: "Ano ang tawag sa malaking lawang tubig na nakapalibot sa Pilipinas?",
    hint: "Ito ay mas malaki kaysa dagat",
    background_image: "placeholder-bg",
    portal_image: "/assets/ocean-sea.png",
    items: [
      { label: "Karagatan", correct_zone: "philippines", is_correct: true },
      { label: "Ilog", is_correct: false },
      { label: "Lawa", is_correct: false },
      { label: "Dagat", is_correct: false },
    ],
  },
  {
    id: 8,
    categoryId: "BASIC",
    levelInCategory: 8,
    title: "Pinakamalaking Isla",
    question: "Ano ang tawag sa pinakamalaking isla sa Pilipinas?",
    hint: "Ito ang isla sa Northern part ng Pilipinas",
    background_image: "placeholder-bg",
    portal_image: "/assets/luzon-island.png",
    items: [
      { label: "Luzon", correct_zone: "philippines", is_correct: true },
      { label: "Mindoro", is_correct: false },
      { label: "Palawan", is_correct: false },
      { label: "Mindanao", is_correct: false },
    ],
  },
  {
    id: 9,
    categoryId: "BASIC",
    levelInCategory: 9,
    title: "Anyong Tubig para sa Transportasyon",
    question: "Anong anyong tubig ang ginagamit sa transportasyon at pangisda?",
    hint: "Dumadaloy ito mula bundok patungo sa dagat",
    background_image: "placeholder-bg",
    portal_image: "/assets/river-transport.png",
    items: [
      { label: "Ilog", correct_zone: "philippines", is_correct: true },
      { label: "Bundok", is_correct: false },
      { label: "Kapatagan", is_correct: false },
      { label: "Disyerto", is_correct: false },
    ],
  },
  {
    id: 10,
    categoryId: "BASIC",
    levelInCategory: 10,
    title: "Chocolate Hills",
    question: "Aling isla ang kilala sa Chocolate Hills?",
    hint: "Ito ay isang isla sa Visayas",
    background_image: "placeholder-bg",
    portal_image: "/assets/chocolate-hills.png",
    items: [
      { label: "Bohol", correct_zone: "philippines", is_correct: true },
      { label: "Cebu", is_correct: false },
      { label: "Mindoro", is_correct: false },
      { label: "Leyte", is_correct: false },
    ],
  },
  {
    id: 11,
    categoryId: "BASIC",
    levelInCategory: 11,
    title: "Tirahan ng Tao",
    question: "Anong anyong lupa ang karaniwang tirahan ng tao?",
    hint: "Ito ay patag na lupa",
    background_image: "placeholder-bg",
    portal_image: "/assets/plains-lowland.png",
    items: [
      { label: "Kapatagan", correct_zone: "philippines", is_correct: true },
      { label: "Bundok", is_correct: false },
      { label: "Disyerto", is_correct: false },
      { label: "Ilog", is_correct: false },
    ],
  },
  {
    id: 12,
    categoryId: "BASIC",
    levelInCategory: 12,
    title: "Kapatagan Malapit sa Ilog",
    question: "Ano ang tawag sa kapatagan na malapit sa ilog?",
    hint: "Ito ay tamis na lupa na maganda para sa pagtatanim",
    background_image: "placeholder-bg",
    portal_image: "/assets/river-valley.png",
    items: [
      { label: "Lambak", correct_zone: "philippines", is_correct: true },
      { label: "Talampas", is_correct: false },
      { label: "Bundok", is_correct: false },
      { label: "Baybayin", is_correct: false },
    ],
  },
  {
    id: 13,
    categoryId: "BASIC",
    levelInCategory: 13,
    title: "Hindi Kabilang sa Luzon",
    question: "Alin sa mga ito ang hindi kabilang sa Luzon?",
    hint: "Ito ay isang probinsya sa Visayas",
    background_image: "placeholder-bg",
    portal_image: "/assets/cebu-island.png",
    items: [
      { label: "Cebu", correct_zone: "philippines", is_correct: true },
      { label: "Quezon", is_correct: false },
      { label: "Palawan", is_correct: false },
      { label: "Ilocos Norte", is_correct: false },
    ],
  },
  {
    id: 14,
    categoryId: "BASIC",
    levelInCategory: 14,
    title: "Maliit na Isla",
    question: "Ano ang tawag sa maliit na isla sa dagat?",
    hint: "Ito ay mas maliit kaysa regular na isla",
    background_image: "placeholder-bg",
    portal_image: "/assets/small-island.png",
    items: [
      { label: "Islet", correct_zone: "philippines", is_correct: true },
      { label: "Peninsula", is_correct: false },
      { label: "Archipelago", is_correct: false },
      { label: "Kapatagan", is_correct: false },
    ],
  },
  {
    id: 15,
    categoryId: "BASIC",
    levelInCategory: 15,
    title: "Kabuuan ng mga Pulo",
    question: "Ano ang tawag sa kabuuan ng mga pulo sa Pilipinas?",
    hint: "Ang Pilipinas ay kapuluan",
    background_image: "placeholder-bg",
    portal_image: "/assets/philippines-archipelago.png",
    items: [
      { label: "Archipelago", correct_zone: "philippines", is_correct: true },
      { label: "Isla", is_correct: false },
      { label: "Peninsula", is_correct: false },
      { label: "Baybayin", is_correct: false },
    ],
  },
];
// ========================================
// 🔵 NORMAL — KULTURA AT LIPUNAN (Culture & Society) - Levels 16-30
// ========================================
const normalCulture: HistoryLevelConfig[] = [
  {
    id: 16,
    categoryId: "NORMAL",
    levelInCategory: 1,
    title: "Pagdiriwang ng Pista",
    question: "Ano ang tawag sa pagdiriwang ng pista sa Pilipinas?",
    hint: "Ito ay tuwing taon na pagdiriwang",
    background_image: "placeholder-bg",
    portal_image: "/assets/fiesta-celebration.png",
    items: [
      { label: "Pistahan", correct_zone: "philippines", is_correct: true },
      { label: "Kaarawan", is_correct: false },
      { label: "Pagtatapos ng Pag-aaral", is_correct: false },
      { label: "Pagpupulong", is_correct: false },
    ],
  },
  {
    id: 17,
    categoryId: "NORMAL",
    levelInCategory: 2,
    title: "Kasuotan sa Fiesta",
    question: "Anong kasuotan ang karaniwang suot sa fiesta?",
    hint: "Ito ang tradisyonal na kasuotan ng mga Pilipino",
    background_image: "placeholder-bg",
    portal_image: "/assets/barong-saya.png",
    items: [
      { label: "Barong at saya", correct_zone: "philippines", is_correct: true },
      { label: "Jeans at T-shirt", is_correct: false },
      { label: "Uniporme sa paaralan", is_correct: false },
      { label: "Pajamas", is_correct: false },
    ],
  },
  {
    id: 18,
    categoryId: "NORMAL",
    levelInCategory: 3,
    title: "Kwento ng mga Ninuno",
    question: "Ano ang tawag sa kwento ng mga ninuno at tradisyon ng isang lugar?",
    hint: "Ito ay kwentong bayan tungkol sa pinagmulan ng mga bagay",
    background_image: "placeholder-bg",
    portal_image: "/assets/legend-alamat.png",
    items: [
      { label: "Alamat", correct_zone: "philippines", is_correct: true },
      { label: "Kasaysayan", is_correct: false },
      { label: "Tula", is_correct: false },
      { label: "Nobela", is_correct: false },
    ],
  },
  {
    id: 19,
    categoryId: "NORMAL",
    levelInCategory: 4,
    title: "Wika sa Luzon",
    question: "Anong wika ang pangunahing sinasalita sa Luzon?",
    hint: "Ito ang base ng national language",
    background_image: "placeholder-bg",
    portal_image: "/assets/tagalog-language.png",
    items: [
      { label: "Tagalog", correct_zone: "philippines", is_correct: true },
      { label: "Cebuano", is_correct: false },
      { label: "Ilocano", is_correct: false },
      { label: "Hiligaynon", is_correct: false },
    ],
  },
  {
    id: 20,
    categoryId: "NORMAL",
    levelInCategory: 5,
    title: "Relihiyon ng mga Pilipino",
    question: "Ano ang tawag sa relihiyon na maraming Pilipino ang pinaniniwalaan?",
    hint: "Ito ang relihiyon na dinala ng mga Espanyol",
    background_image: "placeholder-bg",
    portal_image: "/assets/christianity-cross.png",
    items: [
      { label: "Kristiyanismo", correct_zone: "philippines", is_correct: true },
      { label: "Islam", is_correct: false },
      { label: "Budismo", is_correct: false },
      { label: "Hinduismo", is_correct: false },
    ],
  },
  {
    id: 21,
    categoryId: "NORMAL",
    levelInCategory: 6,
    title: "Grupo ng mga Tao",
    question: "Ano ang tawag sa grupo ng mga tao na may parehong kultura at tradisyon?",
    hint: "Ito ay indigenous group",
    background_image: "placeholder-bg",
    portal_image: "/assets/tribe-group.png",
    items: [
      { label: "Tribu", correct_zone: "philippines", is_correct: true },
      { label: "Lungsod", is_correct: false },
      { label: "Paaralan", is_correct: false },
      { label: "Pamilya", is_correct: false },
    ],
  },
  {
    id: 22,
    categoryId: "NORMAL",
    levelInCategory: 7,
    title: "Sikat na Festival",
    question: "Alin sa mga ito ay isang sikat na festival sa Pilipinas?",
    hint: "Ito ay tuwing Enero sa Cebu",
    background_image: "placeholder-bg",
    portal_image: "/assets/sinulog-festival.png",
    items: [
      { label: "Sinulog", correct_zone: "philippines", is_correct: true },
      { label: "Holi", is_correct: false },
      { label: "Thanksgiving", is_correct: false },
      { label: "Halloween", is_correct: false },
    ],
  },
  {
    id: 23,
    categoryId: "NORMAL",
    levelInCategory: 8,
    title: "Tradisyon sa Pista",
    question: "Ano ang tawag sa tradisyon ng pagbibigay ng pagkain sa mga bisita sa pista?",
    hint: "Ito ay maraming handa para sa mga bisita",
    background_image: "placeholder-bg",
    portal_image: "/assets/handaan-feast.png",
    items: [
      { label: "Handaan", correct_zone: "philippines", is_correct: true },
      { label: "Bayanihan", is_correct: false },
      { label: "Seminar", is_correct: false },
      { label: "Paligsahan", is_correct: false },
    ],
  },
  {
    id: 24,
    categoryId: "NORMAL",
    levelInCategory: 9,
    title: "Sayaw ng mga Bata",
    question: "Ano ang tawag sa simpleng sayaw o laro ng mga bata sa barangay noong sinaunang panahon?",
    hint: "Ito ay tradisyonal na sayaw ng mga katutubo",
    background_image: "placeholder-bg",
    portal_image: "/assets/traditional-dance.png",
    items: [
      { label: "Katutubong Sayaw", correct_zone: "philippines", is_correct: true },
      { label: "Makabagong Sayaw", is_correct: false },
      { label: "Hip-hop", is_correct: false },
      { label: "Baley", is_correct: false },
    ],
  },
  {
    id: 25,
    categoryId: "NORMAL",
    levelInCategory: 10,
    title: "Kasuotan ng Katutubo",
    question: "Alin sa mga ito ang halimbawa ng kasuotan ng mga katutubo sa Cordillera?",
    hint: "Ito ay tradisyonal na damit ng mga Igorot",
    background_image: "placeholder-bg",
    portal_image: "/assets/bahag-tapis.png",
    items: [
      { label: "Bahag at tapis", correct_zone: "philippines", is_correct: true },
      { label: "Barong Tagalog", is_correct: false },
      { label: "Kimono", is_correct: false },
      { label: "Toga", is_correct: false },
    ],
  },
  {
    id: 26,
    categoryId: "NORMAL",
    levelInCategory: 11,
    title: "Pagtulong-tulungan",
    question: "Ano ang tawag sa pagtulong-tulungan ng mga tao sa barangay?",
    hint: "Ito ay Filipino value ng pagtutulungan",
    background_image: "placeholder-bg",
    portal_image: "/assets/bayanihan-helping.png",
    items: [
      { label: "Bayanihan", correct_zone: "philippines", is_correct: true },
      { label: "Pamahalaan", is_correct: false },
      { label: "Negosyo", is_correct: false },
      { label: "Kultura", is_correct: false },
    ],
  },
  {
    id: 27,
    categoryId: "NORMAL",
    levelInCategory: 12,
    title: "Sining ng Gawang-Kamay",
    question: "Ano ang tawag sa sining ng paggawa ng mga tradisyonal na handicraft?",
    hint: "Ito ay produktong gawa ng kamay",
    background_image: "placeholder-bg",
    portal_image: "/assets/handicraft-art.png",
    items: [
      { label: "Gawang-Kamay", correct_zone: "philippines", is_correct: true },
      { label: "Palamuti", is_correct: false },
      { label: "Larawan", is_correct: false },
      { label: "Laro", is_correct: false },
    ],
  },
  {
    id: 28,
    categoryId: "NORMAL",
    levelInCategory: 13,
    title: "Kwento ng mga Bayani",
    question: "Ano ang tawag sa kwento tungkol sa mga bayani at kabayanihan sa lugar?",
    hint: "Ito ay mahabang kwento ng mga bayani",
    background_image: "placeholder-bg",
    portal_image: "/assets/epic-hero.png",
    items: [
      { label: "Epiko", correct_zone: "philippines", is_correct: true },
      { label: "Alamat", is_correct: false },
      { label: "Nobela", is_correct: false },
      { label: "Tula", is_correct: false },
    ],
  },
  {
    id: 29,
    categoryId: "NORMAL",
    levelInCategory: 14,
    title: "Pamumuhay ayon sa Kaugalian",
    question: "Ano ang tawag sa pamumuhay ng mga tao ayon sa nakasanayang kaugalian at gawi?",
    hint: "Ito ang mga tradisyon at beliefs ng tao",
    background_image: "placeholder-bg",
    portal_image: "/assets/culture-tradition.png",
    items: [
      { label: "Kultura", correct_zone: "philippines", is_correct: true },
      { label: "Heograpiya", is_correct: false },
      { label: "Ekonomiya", is_correct: false },
      { label: "Kasaysayan", is_correct: false },
    ],
  },
  {
    id: 30,
    categoryId: "NORMAL",
    levelInCategory: 15,
    title: "Wika sa Kabisayaan",
    question: "Anong wika ang sinasalita sa Kabisayaan?",
    hint: "Ito ay isang major language sa Visayas",
    background_image: "placeholder-bg",
    portal_image: "/assets/hiligaynon-visayan.png",
    items: [
      { label: "Hiligaynon", correct_zone: "philippines", is_correct: true },
      { label: "Tagalog", is_correct: false },
      { label: "Ilocano", is_correct: false },
      { label: "Kapampangan", is_correct: false },
    ],
  },
];

// ========================================
// 🔴 HARD — KASAYSAYAN (History) - Levels 31-45
// ========================================
const hardHistory: HistoryLevelConfig[] = [
  {
    id: 31,
    categoryId: "HARD",
    levelInCategory: 1,
    title: "Pambansang Bayani",
    question: "Sino ang pambansang bayani ng Pilipinas?",
    hint: "Siya ay isang doktor at manunulat",
    background_image: "placeholder-bg",
    portal_image: "/assets/jose-rizal.png",
    items: [
      { label: "Jose Rizal", correct_zone: "philippines", is_correct: true },
      { label: "Andres Bonifacio", is_correct: false },
      { label: "Emilio Aguinaldo", is_correct: false },
      { label: "Apolinario Mabini", is_correct: false },
    ],
  },
  {
    id: 32,
    categoryId: "HARD",
    levelInCategory: 2,
    title: "Pag-aalsa noong 1896",
    question: "Ano ang tawag sa pag-aalsa laban sa mga Kastila noong 1896?",
    hint: "Ito ay nagsimula sa Balintawak",
    background_image: "placeholder-bg",
    portal_image: "/assets/philippine-revolution.png",
    items: [
      { label: "Himagsikang Pilipino", correct_zone: "philippines", is_correct: true },
      { label: "EDSA Revolution", is_correct: false },
      { label: "Laban sa Amerikano", is_correct: false },
      { label: "Sigaw ng Balintawak", is_correct: false },
    ],
  },
  {
    id: 33,
    categoryId: "HARD",
    levelInCategory: 3,
    title: "Unang Republika",
    question: "Ano ang pangalan ng unang republika sa Pilipinas?",
    hint: "Ito ay itinatag noong 1899",
    background_image: "placeholder-bg",
    portal_image: "/assets/malolos-republic.png",
    items: [
      { label: "Republika ng Malolos", correct_zone: "philippines", is_correct: true },
      { label: "Republika ng Pilipinas", is_correct: false },
      { label: "Republika ng Cebu", is_correct: false },
      { label: "Republika ng Katipunan", is_correct: false },
    ],
  },
  {
    id: 34,
    categoryId: "HARD",
    levelInCategory: 4,
    title: "Kilusan ni Bonifacio",
    question: "Ano ang tawag sa kilusan na itinatag ni Andres Bonifacio?",
    hint: "Ang acronym ay KKK",
    background_image: "placeholder-bg",
    portal_image: "/assets/katipunan-kkk.png",
    items: [
      { label: "Katipunan", correct_zone: "philippines", is_correct: true },
      { label: "La Solidaridad", is_correct: false },
      { label: "Propaganda Movement", is_correct: false },
      { label: "KKK", is_correct: false },
    ],
  },
  {
    id: 35,
    categoryId: "HARD",
    levelInCategory: 5,
    title: "Unang Pangulo",
    question: "Sino ang unang pangulo ng Pilipinas?",
    hint: "Siya ay nagdeklara ng kalayaan noong 1898",
    background_image: "placeholder-bg",
    portal_image: "/assets/emilio-aguinaldo.png",
    items: [
      { label: "Emilio Aguinaldo", correct_zone: "philippines", is_correct: true },
      { label: "Manuel Quezon", is_correct: false },
      { label: "Jose Rizal", is_correct: false },
      { label: "Ferdinand Marcos", is_correct: false },
    ],
  },
  {
    id: 36,
    categoryId: "HARD",
    levelInCategory: 6,
    title: "EDSA People Power",
    question: "Ano ang pangyayari noong EDSA People Power?",
    hint: "Ito ay nangyari noong 1986",
    background_image: "placeholder-bg",
    portal_image: "/assets/edsa-revolution.png",
    items: [
      { label: "Pag-aalsa laban sa Marcos", correct_zone: "philippines", is_correct: true },
      { label: "Pagkamatay ni Rizal", is_correct: false },
      { label: "Pagtuklas ng mga Kastila", is_correct: false },
      { label: "Pagbukas ng unang paaralan", is_correct: false },
    ],
  },
  {
    id: 37,
    categoryId: "HARD",
    levelInCategory: 7,
    title: "Sumakop Bago ang Amerikano",
    question: "Anong bansa ang sumakop sa Pilipinas bago dumating ang mga Amerikano?",
    hint: "Sila ay nandito ng mahigit 300 years",
    background_image: "placeholder-bg",
    portal_image: "/assets/spain-colonizer.png",
    items: [
      { label: "Espanya", correct_zone: "philippines", is_correct: true },
      { label: "Hapon", is_correct: false },
      { label: "Pransya", is_correct: false },
      { label: "Netherlands", is_correct: false },
    ],
  },
  {
    id: 38,
    categoryId: "HARD",
    levelInCategory: 8,
    title: "Lihim na Samahan",
    question: "Ano ang tawag sa lihim na samahan ng mga Pilipino laban sa Kastila?",
    hint: "Ang acronym ay KKK",
    background_image: "placeholder-bg",
    portal_image: "/assets/katipunan-secret.png",
    items: [
      { label: "Katipunan", correct_zone: "philippines", is_correct: true },
      { label: "Propaganda Movement", is_correct: false },
      { label: "La Liga Filipina", is_correct: false },
      { label: "KKK", is_correct: false },
    ],
  },
  {
    id: 39,
    categoryId: "HARD",
    levelInCategory: 9,
    title: "Nagpahayag ng Kalayaan",
    question: "Ano ang kilala bilang 'Bayaning Pilipino na nagpahayag ng kalayaan'?",
    hint: "Siya ay unang pangulo",
    background_image: "placeholder-bg",
    portal_image: "/assets/aguinaldo-independence.png",
    items: [
      { label: "Aguinaldo", correct_zone: "philippines", is_correct: true },
      { label: "Rizal", is_correct: false },
      { label: "Bonifacio", is_correct: false },
      { label: "Mabini", is_correct: false },
    ],
  },
  {
    id: 40,
    categoryId: "HARD",
    levelInCategory: 10,
    title: "Sundalo Laban sa Kastila",
    question: "Ano ang tawag sa mga sundalo ng Pilipinas laban sa Kastila?",
    hint: "Sila ay miyembro ng Katipunan",
    background_image: "placeholder-bg",
    portal_image: "/assets/katipunero-soldier.png",
    items: [
      { label: "Katipunero", correct_zone: "philippines", is_correct: true },
      { label: "Hukbalahap", is_correct: false },
      { label: "Guerrilla", is_correct: false },
      { label: "Sundalong Pilipino", is_correct: false },
    ],
  },
  {
    id: 41,
    categoryId: "HARD",
    levelInCategory: 11,
    title: "Labanan noong 1898",
    question: "Ano ang tawag sa labanan sa pagitan ng mga Pilipino at Kastila noong 1898?",
    hint: "Ito ay sa Cavite",
    background_image: "placeholder-bg",
    portal_image: "/assets/battle-imus.png",
    items: [
      { label: "Labanan sa Imus", correct_zone: "philippines", is_correct: true },
      { label: "Labanan sa Balangiga", is_correct: false },
      { label: "Labanan sa Maynila", is_correct: false },
      { label: "Labanan sa Tirad Pass", is_correct: false },
    ],
  },
  {
    id: 42,
    categoryId: "HARD",
    levelInCategory: 12,
    title: "Nagtatag ng La Liga Filipina",
    question: "Sino ang nagtatag ng La Liga Filipina?",
    hint: "Siya rin ang sumulat ng Noli Me Tangere",
    background_image: "placeholder-bg",
    portal_image: "/assets/rizal-la-liga.png",
    items: [
      { label: "Jose Rizal", correct_zone: "philippines", is_correct: true },
      { label: "Andres Bonifacio", is_correct: false },
      { label: "Emilio Aguinaldo", is_correct: false },
      { label: "Marcelo H. del Pilar", is_correct: false },
    ],
  },
  {
    id: 43,
    categoryId: "HARD",
    levelInCategory: 13,
    title: "Kilusang Panitikan",
    question: "Ano ang tawag sa kilusang panitikan ng mga Pilipino sa panahon ng Kastila?",
    hint: "Ito ay gumagamit ng pagsulat upang lumaban",
    background_image: "placeholder-bg",
    portal_image: "/assets/propaganda-movement.png",
    items: [
      { label: "Propaganda Movement", correct_zone: "philippines", is_correct: true },
      { label: "Katipunan", is_correct: false },
      { label: "Panahon ng Kaliwanagan", is_correct: false },
      { label: "Romantisismo", is_correct: false },
    ],
  },
  {
    id: 44,
    categoryId: "HARD",
    levelInCategory: 14,
    title: "Panahon ng Amerikano",
    question: "Ano ang tawag sa panahon ng pananakop ng Amerikano sa Pilipinas?",
    hint: "Ito ay pagkatapos ng Spanish rule",
    background_image: "placeholder-bg",
    portal_image: "/assets/american-period.png",
    items: [
      { label: "Panahon ng Amerikano", correct_zone: "philippines", is_correct: true },
      { label: "Panahon ng Kastila", is_correct: false },
      { label: "Panahon ng Hapon", is_correct: false },
      { label: "Batas Militar", is_correct: false },
    ],
  },
  {
    id: 45,
    categoryId: "HARD",
    levelInCategory: 15,
    title: "Dakilang Lumpo",
    question: "Sino ang tinaguriang 'Dakilang Lumpo'?",
    hint: "Siya ay isang henyo kahit na may kapansanan",
    background_image: "placeholder-bg",
    portal_image: "/assets/apolinario-mabini.png",
    items: [
      { label: "Apolinario Mabini", correct_zone: "philippines", is_correct: true },
      { label: "Jose Rizal", is_correct: false },
      { label: "Emilio Aguinaldo", is_correct: false },
      { label: "Andres Bonifacio", is_correct: false },
    ],
  },
];
// ========================================
// 🟠 ADVANCED — PAMAHALAAN AT PULITIKA (Government & Politics) - Levels 46-60
// ========================================
const advancedGovernment: HistoryLevelConfig[] = [
  {
    id: 46,
    categoryId: "ADVANCED",
    levelInCategory: 1,
    title: "Tatlong Sangay ng Pamahalaan",
    question: "Ano ang tatlong sangay ng pamahalaan?",
    hint: "Executive, Legislative, Judiciary",
    background_image: "placeholder-bg",
    portal_image: "/assets/three-branches.png",
    items: [
      { label: "Ehekutibo, Lehislatura, Hukuman", correct_zone: "philippines", is_correct: true },
      { label: "Pangulo, Kongreso, Hukuman", is_correct: false },
      { label: "Barangay, Lalawigan, Rehiyon", is_correct: false },
      { label: "Alkalde, Gobernador, Pangulo", is_correct: false },
    ],
  },
  {
    id: 47,
    categoryId: "ADVANCED",
    levelInCategory: 2,
    title: "Kasalukuyang Pangulo",
    question: "Sino ang kasalukuyang pangulo ng Pilipinas?",
    hint: "Anak ng dating pangulo",
    background_image: "placeholder-bg",
    portal_image: "/assets/marcos-jr.png",
    items: [
      { label: "Ferdinand Marcos Jr.", correct_zone: "philippines", is_correct: true },
      { label: "Leni Robredo", is_correct: false },
      { label: "Rodrigo Duterte", is_correct: false },
      { label: "Manuel Quezon", is_correct: false },
    ],
  },
  {
    id: 48,
    categoryId: "ADVANCED",
    levelInCategory: 3,
    title: "Pinakamataas na Batas",
    question: "Ano ang tawag sa batas na pinakamataas sa bansa?",
    hint: "Ito ay ang fundamental law ng Pilipinas",
    background_image: "placeholder-bg",
    portal_image: "/assets/constitution-1987.png",
    items: [
      { label: "Saligang Batas 1987", correct_zone: "philippines", is_correct: true },
      { label: "Batas ng Republika", is_correct: false },
      { label: "Ordinansa", is_correct: false },
      { label: "Kautusang Pampanguluhan", is_correct: false },
    ],
  },
  {
    id: 49,
    categoryId: "ADVANCED",
    levelInCategory: 4,
    title: "Tungkulin ng Lehislatura",
    question: "Ano ang tungkulin ng lehislatura?",
    hint: "Sila ay gumagawa ng mga batas",
    background_image: "placeholder-bg",
    portal_image: "/assets/legislature-lawmaking.png",
    items: [
      { label: "Gumawa ng batas", correct_zone: "philippines", is_correct: true },
      { label: "Magpatupad ng batas", is_correct: false },
      { label: "Magbigay ng hustisya", is_correct: false },
      { label: "Mangolekta ng buwis", is_correct: false },
    ],
  },
  {
    id: 50,
    categoryId: "ADVANCED",
    levelInCategory: 5,
    title: "Tungkulin ng Ehekutibo",
    question: "Ano ang tungkulin ng ehekutibo?",
    hint: "Sila ay nagpapatupad ng mga batas",
    background_image: "placeholder-bg",
    portal_image: "/assets/executive-enforce.png",
    items: [
      { label: "Magpatupad ng batas", correct_zone: "philippines", is_correct: true },
      { label: "Gumawa ng batas", is_correct: false },
      { label: "Magpasiya sa korte", is_correct: false },
      { label: "Magsagawa ng survey", is_correct: false },
    ],
  },
  {
    id: 51,
    categoryId: "ADVANCED",
    levelInCategory: 6,
    title: "Karapatang Bumoto",
    question: "Ano ang tawag sa karapatan ng mamamayan na pumili ng pinuno?",
    hint: "Ito ay suffrage o right to vote",
    background_image: "placeholder-bg",
    portal_image: "/assets/voting-rights.png",
    items: [
      { label: "Karapatang Bumoto", correct_zone: "philippines", is_correct: true },
      { label: "Pagsangguni sa Bayan", is_correct: false },
      { label: "Panukala", is_correct: false },
      { label: "Pagbawi ng Opisyal", is_correct: false },
    ],
  },
  {
    id: 52,
    categoryId: "ADVANCED",
    levelInCategory: 7,
    title: "Pagdalo sa Pamahalaan",
    question: "Ano ang tawag sa pagdalo sa pamahalaan para sa kabutihan ng lahat?",
    hint: "Ito ay civic duty",
    background_image: "placeholder-bg",
    portal_image: "/assets/civic-duty.png",
    items: [
      { label: "Tungkulin sa Bayan", correct_zone: "philippines", is_correct: true },
      { label: "Negosyo", is_correct: false },
      { label: "Pamilya", is_correct: false },
      { label: "Pag-aaral", is_correct: false },
    ],
  },
  {
    id: 53,
    categoryId: "ADVANCED",
    levelInCategory: 8,
    title: "Magpataw ng Parusa",
    question: "Sino ang may kapangyarihan magpataw ng parusa sa batas?",
    hint: "Sila ang judicial branch",
    background_image: "placeholder-bg",
    portal_image: "/assets/judiciary-punishment.png",
    items: [
      { label: "Hukuman", correct_zone: "philippines", is_correct: true },
      { label: "Pangulo", is_correct: false },
      { label: "Kongreso", is_correct: false },
      { label: "Punong Barangay", is_correct: false },
    ],
  },
  {
    id: 54,
    categoryId: "ADVANCED",
    levelInCategory: 9,
    title: "Kalayaan sa Pananalita",
    question: "Ano ang tawag sa karapatan ng bawat mamamayan na magsalita ng malaya?",
    hint: "Ito ay freedom of speech",
    background_image: "placeholder-bg",
    portal_image: "/assets/freedom-speech.png",
    items: [
      { label: "Kalayaan sa Pananalita", correct_zone: "philippines", is_correct: true },
      { label: "Kalayaan sa Relihiyon", is_correct: false },
      { label: "Karapatang Bumoto", is_correct: false },
      { label: "Karapatang Mangtipon", is_correct: false },
    ],
  },
  {
    id: 55,
    categoryId: "ADVANCED",
    levelInCategory: 10,
    title: "Checks and Balances",
    question: "Ano ang ibig sabihin ng 'checks and balances'?",
    hint: "Walang sangay na mas malakas sa isa",
    background_image: "placeholder-bg",
    portal_image: "/assets/checks-balances.png",
    items: [
      { label: "Pantay na kapangyarihan", correct_zone: "philippines", is_correct: true },
      { label: "Pagbabayad ng buwis", is_correct: false },
      { label: "Pagbili sa pamilihan", is_correct: false },
      { label: "Pag-aaral sa paaralan", is_correct: false },
    ],
  },
  {
    id: 56,
    categoryId: "ADVANCED",
    levelInCategory: 11,
    title: "Lokal na Pamahalaan ng Barangay",
    question: "Ano ang tawag sa lokal na pamahalaan ng isang barangay?",
    hint: "Ito ang council ng barangay",
    background_image: "placeholder-bg",
    portal_image: "/assets/barangay-council.png",
    items: [
      { label: "Sangguniang Barangay", correct_zone: "philippines", is_correct: true },
      { label: "Konseho ng Bayan", is_correct: false },
      { label: "Pamahalaang Panlalawigan", is_correct: false },
      { label: "Pambansang Pamahalaan", is_correct: false },
    ],
  },
  {
    id: 57,
    categoryId: "ADVANCED",
    levelInCategory: 12,
    title: "Tungkulin ng Presidente",
    question: "Ano ang tungkulin ng presidente sa bansa?",
    hint: "Siya ang head of state",
    background_image: "placeholder-bg",
    portal_image: "/assets/president-role.png",
    items: [
      { label: "Pinuno ng ehekutibo", correct_zone: "philippines", is_correct: true },
      { label: "Gumawa ng batas", is_correct: false },
      { label: "Magdesisyon sa korte", is_correct: false },
      { label: "Mag-organisa ng paligsahan", is_correct: false },
    ],
  },
  {
    id: 58,
    categoryId: "ADVANCED",
    levelInCategory: 13,
    title: "Proseso ng Paggawa ng Batas",
    question: "Ano ang tawag sa proseso ng paggawa ng batas?",
    hint: "Ito ay legislation",
    background_image: "placeholder-bg",
    portal_image: "/assets/legislation-process.png",
    items: [
      { label: "Lehislatura", correct_zone: "philippines", is_correct: true },
      { label: "Hudikatura", is_correct: false },
      { label: "Halalan", is_correct: false },
      { label: "Pamahalaan", is_correct: false },
    ],
  },
  {
    id: 59,
    categoryId: "ADVANCED",
    levelInCategory: 14,
    title: "Rule of Law",
    question: "Ano ang ibig sabihin ng 'Rule of Law'?",
    hint: "Lahat ay sumusunod sa batas",
    background_image: "placeholder-bg",
    portal_image: "/assets/rule-of-law.png",
    items: [
      { label: "Batas ay para sa lahat, kahit sino ay susunod", correct_zone: "philippines", is_correct: true },
      { label: "Pamahalaan lang ang sumusunod sa batas", is_correct: false },
      { label: "Mamamayan lang ang sumusunod sa batas", is_correct: false },
      { label: "Walang batas sa bansa", is_correct: false },
    ],
  },
  {
    id: 60,
    categoryId: "ADVANCED",
    levelInCategory: 15,
    title: "Namumuno sa Kongreso",
    question: "Sino ang namumuno sa Kongreso ng Pilipinas?",
    hint: "May dalawa: Speaker at Senate President",
    background_image: "placeholder-bg",
    portal_image: "/assets/congress-leaders.png",
    items: [
      { label: "Tagapagsalita ng Kamara", correct_zone: "philippines", is_correct: true },
      { label: "Pangulo ng Senado", is_correct: false },
      { label: "Punong Mahistrado", is_correct: false },
      { label: "Pangulo ng Pilipinas", is_correct: false },
    ],
  },
];

// ========================================
// 💀 EXPERT — EKONOMIYA AT GLOBAL STUDIES (Economy & Global) - Levels 61-75
// ========================================
const expertEconomy: HistoryLevelConfig[] = [
  {
    id: 61,
    categoryId: "EXPERT",
    levelInCategory: 1,
    title: "Ibig Sabihin ng GDP",
    question: "Ano ang ibig sabihin ng GDP?",
    hint: "Ito ay total ng produksyon sa bansa",
    background_image: "placeholder-bg",
    portal_image: "/assets/gdp-economy.png",
    items: [
      { label: "Gross Domestic Product", correct_zone: "philippines", is_correct: true },
      { label: "General Domestic Profit", is_correct: false },
      { label: "Great Development Plan", is_correct: false },
      { label: "Global Development Project", is_correct: false },
    ],
  },
  {
    id: 62,
    categoryId: "EXPERT",
    levelInCategory: 2,
    title: "Ibig Sabihin ng GNI",
    question: "Ano ang ibig sabihin ng GNI?",
    hint: "Ito ay total income ng bansa",
    background_image: "placeholder-bg",
    portal_image: "/assets/gni-income.png",
    items: [
      { label: "Gross National Income", correct_zone: "philippines", is_correct: true },
      { label: "General National Income", is_correct: false },
      { label: "Gross New Investment", is_correct: false },
      { label: "Global National Index", is_correct: false },
    ],
  },
  {
    id: 63,
    categoryId: "EXPERT",
    levelInCategory: 3,
    title: "Palitan ng Kalakal",
    question: "Ano ang tawag sa palitan ng kalakal sa pagitan ng mga bansa?",
    hint: "Ito ay international trade",
    background_image: "placeholder-bg",
    portal_image: "/assets/trade-commerce.png",
    items: [
      { label: "Kalakalan", correct_zone: "philippines", is_correct: true },
      { label: "Produksyon", is_correct: false },
      { label: "Pagtitipid", is_correct: false },
      { label: "Konsumo", is_correct: false },
    ],
  },
  {
    id: 64,
    categoryId: "EXPERT",
    levelInCategory: 4,
    title: "Pangunahing Industriya",
    question: "Alin sa mga sumusunod ay halimbawa ng pangunahing industriya sa Pilipinas?",
    hint: "Ito ay farming at pagtatanim",
    background_image: "placeholder-bg",
    portal_image: "/assets/agriculture-farming.png",
    items: [
      { label: "Agrikultura", correct_zone: "philippines", is_correct: true },
      { label: "Software development", is_correct: false },
      { label: "Space exploration", is_correct: false },
      { label: "Mining sa ibang bansa", is_correct: false },
    ],
  },
  {
    id: 65,
    categoryId: "EXPERT",
    levelInCategory: 5,
    title: "Organisasyon sa Timog-Silangang Asya",
    question: "Ano ang tawag sa organisasyon ng mga bansa sa Timog-Silangang Asya?",
    hint: "Ang acronym ay ASEAN",
    background_image: "placeholder-bg",
    portal_image: "/assets/asean-logo.png",
    items: [
      { label: "ASEAN", correct_zone: "philippines", is_correct: true },
      { label: "EU", is_correct: false },
      { label: "UN", is_correct: false },
      { label: "OPEC", is_correct: false },
    ],
  },
  {
    id: 66,
    categoryId: "EXPERT",
    levelInCategory: 6,
    title: "Epekto ng Migrasyon",
    question: "Ano ang epekto ng migrasyon sa bansa?",
    hint: "Ito ay tungkol sa OFW",
    background_image: "placeholder-bg",
    portal_image: "/assets/migration-remittance.png",
    items: [
      { label: "Pagtaas ng populasyon at remittance", correct_zone: "philippines", is_correct: true },
      { label: "Pagbaba ng GDP", is_correct: false },
      { label: "Pagtaas ng bundok", is_correct: false },
      { label: "Pagbago ng klima", is_correct: false },
    ],
  },
  {
    id: 67,
    categoryId: "EXPERT",
    levelInCategory: 7,
    title: "Sistemang Pang-ekonomiya",
    question: "Ano ang tawag sa sistemang pang-ekonomiya kung saan pribado ang negosyo?",
    hint: "Ito ay market economy",
    background_image: "placeholder-bg",
    portal_image: "/assets/market-economy.png",
    items: [
      { label: "Pamilihang Ekonomiya", correct_zone: "philippines", is_correct: true },
      { label: "Ekonomiyang Gobyerno", is_correct: false },
      { label: "Pinagsamang Ekonomiya", is_correct: false },
      { label: "Tradisyunal na Ekonomiya", is_correct: false },
    ],
  },
  {
    id: 68,
    categoryId: "EXPERT",
    levelInCategory: 8,
    title: "Paggawa ng Produkto",
    question: "Ano ang tawag sa paggawa ng produkto o serbisyo?",
    hint: "Ito ay production",
    background_image: "placeholder-bg",
    portal_image: "/assets/production-goods.png",
    items: [
      { label: "Produksyon", correct_zone: "philippines", is_correct: true },
      { label: "Kalakalan", is_correct: false },
      { label: "Pag-iimpok", is_correct: false },
      { label: "Konsumo", is_correct: false },
    ],
  },
  {
    id: 69,
    categoryId: "EXPERT",
    levelInCategory: 9,
    title: "Halaga ng Pera na Kinikita",
    question: "Ano ang tawag sa halaga ng pera na kinikita ng isang bansa sa loob at labas ng bansa?",
    hint: "Ito ay GNI",
    background_image: "placeholder-bg",
    portal_image: "/assets/national-income.png",
    items: [
      { label: "Gross National Income", correct_zone: "philippines", is_correct: true },
      { label: "Gross Domestic Product", is_correct: false },
      { label: "Inflation", is_correct: false },
      { label: "Tax", is_correct: false },
    ],
  },
  {
    id: 70,
    categoryId: "EXPERT",
    levelInCategory: 10,
    title: "Global Issue",
    question: "Alin sa mga sumusunod ang halimbawa ng global issue?",
    hint: "Ito ay tungkol sa klima ng mundo",
    background_image: "placeholder-bg",
    portal_image: "/assets/climate-change.png",
    items: [
      { label: "Climate change", correct_zone: "philippines", is_correct: true },
      { label: "Laro sa paaralan", is_correct: false },
      { label: "Pistahan", is_correct: false },
      { label: "Kaarawan", is_correct: false },
    ],
  },
  {
    id: 71,
    categoryId: "EXPERT",
    levelInCategory: 11,
    title: "Pera sa Pakikipagkalakalan",
    question: "Ano ang tawag sa pera na ginagamit sa pakikipagkalakalan?",
    hint: "Ito ay currency o money",
    background_image: "placeholder-bg",
    portal_image: "/assets/currency-money.png",
    items: [
      { label: "Salapi", correct_zone: "philippines", is_correct: true },
      { label: "Ipon", is_correct: false },
      { label: "Pamumuhuan", is_correct: false },
      { label: "Badyet", is_correct: false },
    ],
  },
  {
    id: 72,
    categoryId: "EXPERT",
    levelInCategory: 12,
    title: "Pinagkukunan ng Yaman",
    question: "Alin sa mga sumusunod ang pangunahing pinagkukunan ng yaman ng Pilipinas?",
    hint: "Tatlong sektor ng ekonomiya",
    background_image: "placeholder-bg",
    portal_image: "/assets/economic-sectors.png",
    items: [
      { label: "Agrikultura, Serbisyo, Industriya", correct_zone: "philippines", is_correct: true },
      { label: "Paglalakbay", is_correct: false },
      { label: "Sine, Musika, Palakasan", is_correct: false },
      { label: "Turismo", is_correct: false },
    ],
  },
  {
    id: 73,
    categoryId: "EXPERT",
    levelInCategory: 13,
    title: "Sistema ng Pagtustos",
    question: "Ano ang tawag sa sistema ng pagtustos sa mga pangangailangan ng tao?",
    hint: "Ito ay economics",
    background_image: "placeholder-bg",
    portal_image: "/assets/economic-system.png",
    items: [
      { label: "Ekonomiya", correct_zone: "philippines", is_correct: true },
      { label: "Heograpiya", is_correct: false },
      { label: "Kultura", is_correct: false },
      { label: "Pulitika", is_correct: false },
    ],
  },
  {
    id: 74,
    categoryId: "EXPERT",
    levelInCategory: 14,
    title: "Ibig Sabihin ng Remittance",
    question: "Ano ang ibig sabihin ng remittance?",
    hint: "Ito ay pera mula sa mga OFW",
    background_image: "placeholder-bg",
    portal_image: "/assets/ofw-remittance.png",
    items: [
      { label: "Pera galing sa OFW", correct_zone: "philippines", is_correct: true },
      { label: "Tax na binabayad sa gobyerno", is_correct: false },
      { label: "Produkto mula sa pamilihan", is_correct: false },
      { label: "Kita mula sa Negosyo", is_correct: false },
    ],
  },
  {
    id: 75,
    categoryId: "EXPERT",
    levelInCategory: 15,
    title: "Pandaigdigang Ugnayan",
    question: "Alin sa mga sumusunod ang kabilang sa pandaigdigang ugnayan ng Pilipinas?",
    hint: "Ito ay regional organization",
    background_image: "placeholder-bg",
    portal_image: "/assets/philippines-asean.png",
    items: [
      { label: "Kasapian sa ASEAN", correct_zone: "philippines", is_correct: true },
      { label: "Pistahan sa Barangay", is_correct: false },
      { label: "Pagtatapos sa Paaralan", is_correct: false },
      { label: "Kalakalan sa pamilihan", is_correct: false },
    ],
  },
];
// ========================================
// Generate all 75 levels (15 per category × 5 categories)
// ========================================
const levels: HistoryLevelConfig[] = [
  ...basicGeography,      // Levels 1-15
  ...normalCulture,       // Levels 16-30
  ...hardHistory,         // Levels 31-45
  ...advancedGovernment,  // Levels 46-60
  ...expertEconomy,       // Levels 61-75
];

export default levels;

// ========================================
// Helper Functions
// ========================================

// Helper function to get a level by ID
export function getLevelConfig(levelId: number): HistoryLevelConfig {
  return levels.find((l) => l.id === levelId) || levels[0];
}

// Helper function to get levels by category
export function getLevelsByCategory(categoryId: string): HistoryLevelConfig[] {
  return levels.filter((l) => l.categoryId === categoryId);
}

// Helper function to get a level by category and level number
export function getLevelByCategory(categoryId: string, levelInCategory: number): HistoryLevelConfig | undefined {
  return levels.find((l) => l.categoryId === categoryId && l.levelInCategory === levelInCategory);
}

// Helper function to get all categories
export function getAllCategories(): string[] {
  return ["BASIC", "NORMAL", "HARD", "ADVANCED", "EXPERT"];
}

// Helper function to get category info
export function getCategoryInfo(categoryId: string): { name: string; subtitle: string; color: string } {
  const categoryMap: Record<string, { name: string; subtitle: string; color: string }> = {
    BASIC: {
      name: "🟢 BASIC",
      subtitle: "Heograpiya (Geography)",
      color: "#4CAF50",
    },
    NORMAL: {
      name: "🔵 NORMAL",
      subtitle: "Kultura at Lipunan (Culture)",
      color: "#2196F3",
    },
    HARD: {
      name: "🔴 HARD",
      subtitle: "Kasaysayan (History)",
      color: "#F44336",
    },
    ADVANCED: {
      name: "🟠 ADVANCED",
      subtitle: "Pamahalaan (Government)",
      color: "#FF9800",
    },
    EXPERT: {
      name: "💀 EXPERT",
      subtitle: "Ekonomiya (Economy)",
      color: "#9C27B0",
    },
  };
  
  return categoryMap[categoryId] || categoryMap.BASIC;
}

// ========================================
// LEGACY SUPPORT - For backwards compatibility
// ========================================

// Export old HISTORY_LEVELS format for any code still using it
export const HISTORY_LEVELS: Record<string, any> = {};

levels.forEach((level) => {
  const key = `history-${level.id}`;
  HISTORY_LEVELS[key] = {
    title: `LEVEL ${level.id}: ${level.title}`,
    question: level.question,
    hint: level.hint,
    background_image: level.background_image,
    portal_image: level.portal_image,
    items: level.items,
    next_level: level.id < 75 ? `history-${level.id + 1}` : undefined,
  };
});