// levels.ts
export interface LevelConfig {
  id: number;
  categoryId: string;
  levelInCategory: number;
  minNumber: number;
  maxNumber: number;
  fruitMultiplier: number;
  allowRotten: boolean;
  operation: 'addition' | 'subtraction' | 'multiplication' | 'division' | 'mixed' | 'fixed';
  difficulty: 'BASIC' | 'NORMAL' | 'HARD' | 'ADVANCED' | 'EXPERT';
  spawnDelay?: number;
  
  // NEW: Support multiple questions for randomization
  questions?: Array<{ question: string; answer: number }>;
  
  // For backward compatibility (single question)
  question?: string;
  answer?: number;
}

const levels: LevelConfig[] = [
  // ========================================
  // 🟢 BASIC — Addition & Subtraction (Levels 1-10) — RANDOMIZED
  // ========================================
  {
    id: 1,
    categoryId: 'BASIC',
    levelInCategory: 1,
    minNumber: 1,
    maxNumber: 5,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'addition',
    difficulty: 'BASIC',
    spawnDelay: 1400,
  },
  {
    id: 2,
    categoryId: 'BASIC',
    levelInCategory: 2,
    minNumber: 3,
    maxNumber: 8,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'addition',
    difficulty: 'BASIC',
    spawnDelay: 1300,
  },
  {
    id: 3,
    categoryId: 'BASIC',
    levelInCategory: 3,
    minNumber: 5,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'subtraction',
    difficulty: 'BASIC',
    spawnDelay: 1300,
  },
  {
    id: 4,
    categoryId: 'BASIC',
    levelInCategory: 4,
    minNumber: 5,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'subtraction',
    difficulty: 'BASIC',
    spawnDelay: 1200,
  },
  {
    id: 5,
    categoryId: 'BASIC',
    levelInCategory: 5,
    minNumber: 5,
    maxNumber: 12,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 1200,
  },
  {
    id: 6,
    categoryId: 'BASIC',
    levelInCategory: 6,
    minNumber: 8,
    maxNumber: 15,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'addition',
    difficulty: 'BASIC',
    spawnDelay: 1100,
  },
  {
    id: 7,
    categoryId: 'BASIC',
    levelInCategory: 7,
    minNumber: 10,
    maxNumber: 18,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'subtraction',
    difficulty: 'BASIC',
    spawnDelay: 1100,
  },
  {
    id: 8,
    categoryId: 'BASIC',
    levelInCategory: 8,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 1000,
  },
  {
    id: 9,
    categoryId: 'BASIC',
    levelInCategory: 9,
    minNumber: 12,
    maxNumber: 22,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 1000,
  },
  {
    id: 10,
    categoryId: 'BASIC',
    levelInCategory: 10,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 950,
  },
  {
    id: 11,
    categoryId: 'BASIC',
    levelInCategory: 11,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 950,
  },
  {
    id: 12,
    categoryId: 'BASIC',
    levelInCategory: 12,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 950,
  },
  {
    id: 13,
    categoryId: 'BASIC',
    levelInCategory: 13,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 950,
  },
  {
    id: 14,
    categoryId: 'BASIC',
    levelInCategory: 14,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 950,
  },
  {
    id: 15,
    categoryId: 'BASIC',
    levelInCategory: 15,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'BASIC',
    spawnDelay: 950,
  },
  // ========================================
  // 🟡 NORMAL — Multiplication & Division (Levels 16-30) — RANDOMIZED
  // ========================================
  {
    id: 16,
    categoryId: 'NORMAL',
    levelInCategory: 1,
    minNumber: 2,
    maxNumber: 4,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'multiplication',
    difficulty: 'NORMAL',
    spawnDelay: 1300,
  },
  {
    id: 17,
    categoryId: 'NORMAL',
    levelInCategory: 2,
    minNumber: 3,
    maxNumber: 5,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'multiplication',
    difficulty: 'NORMAL',
    spawnDelay: 1200,
  },
  {
    id: 18,
    categoryId: 'NORMAL',
    levelInCategory: 3,
    minNumber: 4,
    maxNumber: 6,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'multiplication',
    difficulty: 'NORMAL',
    spawnDelay: 1200,
  },
  {
    id: 19,
    categoryId: 'NORMAL',
    levelInCategory: 4,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'division',
    difficulty: 'NORMAL',
    spawnDelay: 1200,
  },
  {
    id: 20,
    categoryId: 'NORMAL',
    levelInCategory: 5,
    minNumber: 15,
    maxNumber: 30,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'division',
    difficulty: 'NORMAL',
    spawnDelay: 1100,
  },
  {
    id: 21,
    categoryId: 'NORMAL',
    levelInCategory: 6,
    minNumber: 5,
    maxNumber: 8,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'multiplication',
    difficulty: 'NORMAL',
    spawnDelay: 1000,
  },
  {
    id: 22,
    categoryId: 'NORMAL',
    levelInCategory: 7,
    minNumber: 20,
    maxNumber: 40,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'division',
    difficulty: 'NORMAL',
    spawnDelay: 1000,
  },
  {
    id: 23,
    categoryId: 'NORMAL',
    levelInCategory: 8,
    minNumber: 6,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'multiplication',
    difficulty: 'NORMAL',
    spawnDelay: 950,
  },
  {
    id: 24,
    categoryId: 'NORMAL',
    levelInCategory: 9,
    minNumber: 25,
    maxNumber: 50,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'division',
    difficulty: 'NORMAL',
    spawnDelay: 900,
  },
  {
    id: 25,
    categoryId: 'NORMAL',
    levelInCategory: 10,
    minNumber: 8,
    maxNumber: 12,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'NORMAL',
    spawnDelay: 900,
  },
  {
    id: 26,
    categoryId: 'NORMAL',
    levelInCategory: 11,
    minNumber: 7,
    maxNumber: 12,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'multiplication',
    difficulty: 'NORMAL',
    spawnDelay: 850,
  },
  {
    id: 27,
    categoryId: 'NORMAL',
    levelInCategory: 12,
    minNumber: 30,
    maxNumber: 60,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'division',
    difficulty: 'NORMAL',
    spawnDelay: 850,
  },
  {
    id: 28,
    categoryId: 'NORMAL',
    levelInCategory: 13,
    minNumber: 9,
    maxNumber: 15,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'multiplication',
    difficulty: 'NORMAL',
    spawnDelay: 800,
  },
  {
    id: 29,
    categoryId: 'NORMAL',
    levelInCategory: 14,
    minNumber: 40,
    maxNumber: 80,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'division',
    difficulty: 'NORMAL',
    spawnDelay: 800,
  },
  {
    id: 30,
    categoryId: 'NORMAL',
    levelInCategory: 15,
    minNumber: 10,
    maxNumber: 15,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'mixed',
    difficulty: 'NORMAL',
    spawnDelay: 750,
  },

  // ========================================
  // 🟠 HARD — Fractions & Decimals (Levels 31-45) — RANDOMIZED QUESTION POOLS
  // ========================================
  {
    id: 31,
    categoryId: 'HARD',
    levelInCategory: 1,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 1100,
    questions: [
      { question: '1/2 of 10 = ?', answer: 5 },
      { question: '1/2 of 8 = ?', answer: 4 },
      { question: '1/2 of 12 = ?', answer: 6 },
      { question: '1/2 of 6 = ?', answer: 3 },
    ],
  },
  {
    id: 32,
    categoryId: 'HARD',
    levelInCategory: 2,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 1100,
    questions: [
      { question: '1/2 of 14 = ?', answer: 7 },
      { question: '1/2 of 16 = ?', answer: 8 },
      { question: '1/2 of 18 = ?', answer: 9 },
      { question: '1/2 of 20 = ?', answer: 10 },
    ],
  },
  {
    id: 33,
    categoryId: 'HARD',
    levelInCategory: 3,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 1000,
    questions: [
      { question: '3/4 of 20 = ?', answer: 15 },
      { question: '3/4 of 16 = ?', answer: 12 },
      { question: '3/4 of 24 = ?', answer: 18 },
      { question: '3/4 of 12 = ?', answer: 9 },
    ],
  },
  {
    id: 34,
    categoryId: 'HARD',
    levelInCategory: 4,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 1000,
    questions: [
      { question: '1/4 of 16 = ?', answer: 4 },
      { question: '1/4 of 20 = ?', answer: 5 },
      { question: '1/4 of 12 = ?', answer: 3 },
      { question: '1/4 of 8 = ?', answer: 2 },
    ],
  },
  {
    id: 35,
    categoryId: 'HARD',
    levelInCategory: 5,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 950,
    questions: [
      { question: '2/3 of 12 = ?', answer: 8 },
      { question: '2/3 of 15 = ?', answer: 10 },
      { question: '2/3 of 9 = ?', answer: 6 },
      { question: '2/3 of 18 = ?', answer: 12 },
    ],
  },
  {
    id: 36,
    categoryId: 'HARD',
    levelInCategory: 6,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 950,
    questions: [
      { question: '1/3 of 15 = ?', answer: 5 },
      { question: '1/3 of 18 = ?', answer: 6 },
      { question: '1/3 of 12 = ?', answer: 4 },
      { question: '1/3 of 9 = ?', answer: 3 },
    ],
  },
  {
    id: 37,
    categoryId: 'HARD',
    levelInCategory: 7,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 900,
    questions: [
      { question: '3/5 of 10 = ?', answer: 6 },
      { question: '3/5 of 15 = ?', answer: 9 },
      { question: '3/5 of 20 = ?', answer: 12 },
      { question: '3/5 of 5 = ?', answer: 3 },
    ],
  },
  {
    id: 38,
    categoryId: 'HARD',
    levelInCategory: 8,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 900,
    questions: [
      { question: '0.5 × 10 = ?', answer: 5 },
      { question: '0.5 × 8 = ?', answer: 4 },
      { question: '0.5 × 12 = ?', answer: 6 },
      { question: '0.5 × 14 = ?', answer: 7 },
    ],
  },
  {
    id: 39,
    categoryId: 'HARD',
    levelInCategory: 9,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 850,
    questions: [
      { question: '0.25 × 20 = ?', answer: 5 },
      { question: '0.25 × 16 = ?', answer: 4 },
      { question: '0.25 × 24 = ?', answer: 6 },
      { question: '0.25 × 12 = ?', answer: 3 },
    ],
  },
  {
    id: 40,
    categoryId: 'HARD',
    levelInCategory: 10,
    minNumber: 1,
    maxNumber: 15,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 850,
    questions: [
      { question: '0.5 + 0.5 = ?', answer: 1 },
      { question: '0.25 + 0.75 = ?', answer: 1 },
      { question: '0.3 + 0.7 = ?', answer: 1 },
      { question: '0.6 + 0.4 = ?', answer: 1 },
    ],
  },
  {
    id: 41,
    categoryId: 'HARD',
    levelInCategory: 11,
    minNumber: 5,
    maxNumber: 15,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 800,
    questions: [
      { question: '1.5 × 4 = ?', answer: 6 },
      { question: '1.5 × 6 = ?', answer: 9 },
      { question: '1.5 × 8 = ?', answer: 12 },
      { question: '1.5 × 2 = ?', answer: 3 },
    ],
  },
  {
    id: 42,
    categoryId: 'HARD',
    levelInCategory: 12,
    minNumber: 5,
    maxNumber: 15,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 800,
    questions: [
      { question: '2.5 × 4 = ?', answer: 10 },
      { question: '2.5 × 6 = ?', answer: 15 },
      { question: '2.5 × 2 = ?', answer: 5 },
      { question: '2.5 × 8 = ?', answer: 20 },
    ],
  },
  {
    id: 43,
    categoryId: 'HARD',
    levelInCategory: 13,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 750,
    questions: [
      { question: '0.75 × 8 = ?', answer: 6 },
      { question: '0.75 × 12 = ?', answer: 9 },
      { question: '0.75 × 4 = ?', answer: 3 },
      { question: '0.75 × 16 = ?', answer: 12 },
    ],
  },
  {
    id: 44,
    categoryId: 'HARD',
    levelInCategory: 14,
    minNumber: 5,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 750,
    questions: [
      { question: '0.2 × 10 = ?', answer: 2 },
      { question: '0.2 × 15 = ?', answer: 3 },
      { question: '0.2 × 20 = ?', answer: 4 },
      { question: '0.2 × 25 = ?', answer: 5 },
    ],
  },
  {
    id: 45,
    categoryId: 'HARD',
    levelInCategory: 15,
    minNumber: 5,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'HARD',
    spawnDelay: 700,
    questions: [
      { question: '0.1 + 0.9 = ?', answer: 1 },
      { question: '0.4 + 0.6 = ?', answer: 1 },
      { question: '0.2 + 0.8 = ?', answer: 1 },
      { question: '1.5 + 1.5 = ?', answer: 3 },
    ],
  },

  // ========================================
  // 🔴 ADVANCED — Ratios & Percent (Levels 46-60) — RANDOMIZED QUESTION POOLS
  // ========================================
  {
    id: 46,
    categoryId: 'ADVANCED',
    levelInCategory: 1,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 900,
    questions: [
      { question: '10% of 50 = ?', answer: 5 },
      { question: '10% of 30 = ?', answer: 3 },
      { question: '10% of 40 = ?', answer: 4 },
      { question: '10% of 60 = ?', answer: 6 },
    ],
  },
  {
    id: 47,
    categoryId: 'ADVANCED',
    levelInCategory: 2,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 900,
    questions: [
      { question: '20% of 50 = ?', answer: 10 },
      { question: '20% of 30 = ?', answer: 6 },
      { question: '20% of 40 = ?', answer: 8 },
      { question: '20% of 60 = ?', answer: 12 },
    ],
  },
  {
    id: 48,
    categoryId: 'ADVANCED',
    levelInCategory: 3,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 850,
    questions: [
      { question: '25% of 40 = ?', answer: 10 },
      { question: '25% of 20 = ?', answer: 5 },
      { question: '25% of 60 = ?', answer: 15 },
      { question: '25% of 80 = ?', answer: 20 },
    ],
  },
  {
    id: 49,
    categoryId: 'ADVANCED',
    levelInCategory: 4,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 850,
    questions: [
      { question: '50% of 30 = ?', answer: 15 },
      { question: '50% of 20 = ?', answer: 10 },
      { question: '50% of 40 = ?', answer: 20 },
      { question: '50% of 60 = ?', answer: 30 },
    ],
  },
  {
    id: 50,
    categoryId: 'ADVANCED',
    levelInCategory: 5,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 800,
    questions: [
      { question: '75% of 20 = ?', answer: 15 },
      { question: '75% of 16 = ?', answer: 12 },
      { question: '75% of 24 = ?', answer: 18 },
      { question: '75% of 12 = ?', answer: 9 },
    ],
  },
  {
    id: 51,
    categoryId: 'ADVANCED',
    levelInCategory: 6,
    minNumber: 10,
    maxNumber: 30,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 800,
    questions: [
      { question: '20% of 80 = ?', answer: 16 },
      { question: '20% of 100 = ?', answer: 20 },
      { question: '20% of 90 = ?', answer: 18 },
      { question: '20% of 70 = ?', answer: 14 },
    ],
  },
  {
    id: 52,
    categoryId: 'ADVANCED',
    levelInCategory: 7,
    minNumber: 20,
    maxNumber: 40,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 750,
    questions: [
      { question: '30% of 100 = ?', answer: 30 },
      { question: '30% of 50 = ?', answer: 15 },
      { question: '30% of 70 = ?', answer: 21 },
      { question: '30% of 60 = ?', answer: 18 },
    ],
  },
  {
    id: 53,
    categoryId: 'ADVANCED',
    levelInCategory: 8,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 750,
    questions: [
      { question: 'Ratio 1:1, total 10 → each = ?', answer: 5 },
      { question: 'Ratio 1:1, total 12 → each = ?', answer: 6 },
      { question: 'Ratio 1:1, total 14 → each = ?', answer: 7 },
      { question: 'Ratio 1:1, total 8 → each = ?', answer: 4 },
    ],
  },
  {
    id: 54,
    categoryId: 'ADVANCED',
    levelInCategory: 9,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 700,
    questions: [
      { question: 'Ratio 1:2, total 15 → larger = ?', answer: 10 },
      { question: 'Ratio 1:2, total 12 → larger = ?', answer: 8 },
      { question: 'Ratio 1:2, total 18 → larger = ?', answer: 12 },
      { question: 'Ratio 1:2, total 9 → larger = ?', answer: 6 },
    ],
  },
  {
    id: 55,
    categoryId: 'ADVANCED',
    levelInCategory: 10,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 700,
    questions: [
      { question: 'Ratio 2:3, total 25 → larger = ?', answer: 15 },
      { question: 'Ratio 2:3, total 20 → larger = ?', answer: 12 },
      { question: 'Ratio 2:3, total 30 → larger = ?', answer: 18 },
      { question: 'Ratio 2:3, total 15 → larger = ?', answer: 9 },
    ],
  },
  {
    id: 56,
    categoryId: 'ADVANCED',
    levelInCategory: 11,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 650,
    questions: [
      { question: 'Ratio 1:3, total 12 → larger = ?', answer: 9 },
      { question: 'Ratio 1:3, total 16 → larger = ?', answer: 12 },
      { question: 'Ratio 1:3, total 20 → larger = ?', answer: 15 },
      { question: 'Ratio 1:3, total 8 → larger = ?', answer: 6 },
    ],
  },
  {
    id: 57,
    categoryId: 'ADVANCED',
    levelInCategory: 12,
    minNumber: 30,
    maxNumber: 50,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 650,
    questions: [
      { question: '5% off 40 = ?', answer: 38 },
      { question: '5% off 60 = ?', answer: 57 },
      { question: '5% off 80 = ?', answer: 76 },
      { question: '5% off 20 = ?', answer: 19 },
    ],
  },
  {
    id: 58,
    categoryId: 'ADVANCED',
    levelInCategory: 13,
    minNumber: 40,
    maxNumber: 60,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 600,
    questions: [
      { question: '10% off 50 = ?', answer: 45 },
      { question: '10% off 40 = ?', answer: 36 },
      { question: '10% off 60 = ?', answer: 54 },
      { question: '10% off 30 = ?', answer: 27 },
    ],
  },
  {
    id: 59,
    categoryId: 'ADVANCED',
    levelInCategory: 14,
    minNumber: 40,
    maxNumber: 50,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 600,
    questions: [
      { question: 'Increase 40 by 10% = ?', answer: 44 },
      { question: 'Increase 50 by 10% = ?', answer: 55 },
      { question: 'Increase 30 by 10% = ?', answer: 33 },
      { question: 'Increase 60 by 10% = ?', answer: 66 },
    ],
  },
  {
    id: 60,
    categoryId: 'ADVANCED',
    levelInCategory: 15,
    minNumber: 50,
    maxNumber: 70,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'ADVANCED',
    spawnDelay: 550,
    questions: [
      { question: 'Increase 50 by 20% = ?', answer: 60 },
      { question: 'Increase 40 by 25% = ?', answer: 50 },
      { question: 'Increase 60 by 10% = ?', answer: 66 },
      { question: 'Increase 30 by 50% = ?', answer: 45 },
    ],
  },

  // ========================================
  // 🟣 EXPERT — Measurement & Geometry (Levels 61-75) — RANDOMIZED QUESTION POOLS
  // ========================================
  {
    id: 61,
    categoryId: 'EXPERT',
    levelInCategory: 1,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 900,
    questions: [
      { question: 'Rectangle 5 × 2 → perimeter = ?', answer: 14 },
      { question: 'Rectangle 4 × 3 → perimeter = ?', answer: 14 },
      { question: 'Rectangle 6 × 1 → perimeter = ?', answer: 14 },
      { question: 'Rectangle 3 × 4 → perimeter = ?', answer: 14 },
    ],
  },
  {
    id: 62,
    categoryId: 'EXPERT',
    levelInCategory: 2,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 900,
    questions: [
      { question: 'Rectangle 6 × 4 → perimeter = ?', answer: 20 },
      { question: 'Rectangle 5 × 5 → perimeter = ?', answer: 20 },
      { question: 'Rectangle 7 × 3 → perimeter = ?', answer: 20 },
      { question: 'Rectangle 8 × 2 → perimeter = ?', answer: 20 },
    ],
  },
  {
    id: 63,
    categoryId: 'EXPERT',
    levelInCategory: 3,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 850,
    questions: [
      { question: 'Rectangle 7 × 4 → perimeter = ?', answer: 22 },
      { question: 'Rectangle 6 × 5 → perimeter = ?', answer: 22 },
      { question: 'Rectangle 8 × 3 → perimeter = ?', answer: 22 },
      { question: 'Rectangle 9 × 2 → perimeter = ?', answer: 22 },
    ],
  },
  {
    id: 64,
    categoryId: 'EXPERT',
    levelInCategory: 4,
    minNumber: 10,
    maxNumber: 20,
    fruitMultiplier: 1,
    allowRotten: false,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 850,
    questions: [
      { question: 'Rectangle 4 × 3 → area = ?', answer: 12 },
      { question: 'Rectangle 6 × 2 → area = ?', answer: 12 },
      { question: 'Rectangle 3 × 4 → area = ?', answer: 12 },
      { question: 'Rectangle 2 × 6 → area = ?', answer: 12 },
    ],
  },
  {
    id: 65,
    categoryId: 'EXPERT',
    levelInCategory: 5,
    minNumber: 15,
    maxNumber: 25,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 800,
    questions: [
      { question: 'Rectangle 5 × 4 → area = ?', answer: 20 },
      { question: 'Rectangle 4 × 5 → area = ?', answer: 20 },
      { question: 'Rectangle 10 × 2 → area = ?', answer: 20 },
      { question: 'Rectangle 2 × 10 → area = ?', answer: 20 },
    ],
  },
  {
    id: 66,
    categoryId: 'EXPERT',
    levelInCategory: 6,
    minNumber: 30,
    maxNumber: 40,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 800,
    questions: [
      { question: 'Rectangle 5 × 7 → area = ?', answer: 35 },
      { question: 'Rectangle 7 × 5 → area = ?', answer: 35 },
      { question: 'Rectangle 5 × 6 → area = ?', answer: 30 },
      { question: 'Rectangle 6 × 6 → area = ?', answer: 36 },
    ],
  },
  {
    id: 67,
    categoryId: 'EXPERT',
    levelInCategory: 7,
    minNumber: 40,
    maxNumber: 50,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 750,
    questions: [
      { question: 'Rectangle 6 × 8 → area = ?', answer: 48 },
      { question: 'Rectangle 8 × 6 → area = ?', answer: 48 },
      { question: 'Rectangle 7 × 7 → area = ?', answer: 49 },
      { question: 'Rectangle 9 × 5 → area = ?', answer: 45 },
    ],
  },
  {
    id: 68,
    categoryId: 'EXPERT',
    levelInCategory: 8,
    minNumber: 20,
    maxNumber: 30,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 750,
    questions: [
      { question: 'Box 4 × 3 × 2 → volume = ?', answer: 24 },
      { question: 'Box 3 × 4 × 2 → volume = ?', answer: 24 },
      { question: 'Box 2 × 3 × 4 → volume = ?', answer: 24 },
      { question: 'Box 6 × 2 × 2 → volume = ?', answer: 24 },
    ],
  },
  {
    id: 69,
    categoryId: 'EXPERT',
    levelInCategory: 9,
    minNumber: 20,
    maxNumber: 40,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 700,
    questions: [
      { question: 'Box 3 × 3 × 3 → volume = ?', answer: 27 },
      { question: 'Box 4 × 4 × 4 → volume = ?', answer: 64 },
      { question: 'Box 2 × 2 × 2 → volume = ?', answer: 8 },
      { question: 'Box 5 × 4 × 2 → volume = ?', answer: 40 },
    ],
  },
  {
    id: 70,
    categoryId: 'EXPERT',
    levelInCategory: 10,
    minNumber: 50,
    maxNumber: 80,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 700,
    questions: [
      { question: 'Box 5 × 5 × 5 → volume = ?', answer: 125 },
      { question: 'Box 6 × 6 × 6 → volume = ?', answer: 216 },
      { question: 'Box 4 × 5 × 3 → volume = ?', answer: 60 },
      { question: 'Box 6 × 4 × 3 → volume = ?', answer: 72 },
    ],
  },
  {
    id: 71,
    categoryId: 'EXPERT',
    levelInCategory: 11,
    minNumber: 100,
    maxNumber: 120,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 650,
    questions: [
      { question: 'Angle 180°, one = 65° → other = ?', answer: 115 },
      { question: 'Angle 180°, one = 75° → other = ?', answer: 105 },
      { question: 'Angle 180°, one = 110° → other = ?', answer: 70 },
      { question: 'Angle 180°, one = 120° → other = ?', answer: 60 },
    ],
  },
  {
    id: 72,
    categoryId: 'EXPERT',
    levelInCategory: 12,
    minNumber: 80,
    maxNumber: 100,
    fruitMultiplier: 10,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 650,
    questions: [
      { question: 'Angle 180°, one = 90° → other = ?', answer: 90 },
      { question: 'Angle 180°, one = 100° → other = ?', answer: 80 },
      { question: 'Angle 180°, one = 85° → other = ?', answer: 95 },
      { question: 'Angle 180°, one = 70° → other = ?', answer: 110 },
    ],
  },
  {
    id: 73,
    categoryId: 'EXPERT',
    levelInCategory: 13,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 600,
    questions: [
      { question: 'Distance (2,3) to (2,8) = ?', answer: 5 },
      { question: 'Distance (1,2) to (1,6) = ?', answer: 4 },
      { question: 'Distance (3,1) to (3,7) = ?', answer: 6 },
      { question: 'Distance (0,0) to (0,3) = ?', answer: 3 },
    ],
  },
  {
    id: 74,
    categoryId: 'EXPERT',
    levelInCategory: 14,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 600,
    questions: [
      { question: 'Distance (5,2) to (5,10) = ?', answer: 8 },
      { question: 'Distance (3,4) to (3,11) = ?', answer: 7 },
      { question: 'Distance (0,1) to (0,10) = ?', answer: 9 },
      { question: 'Distance (2,5) to (2,15) = ?', answer: 10 },
    ],
  },
  {
    id: 75,
    categoryId: 'EXPERT',
    levelInCategory: 15,
    minNumber: 1,
    maxNumber: 10,
    fruitMultiplier: 1,
    allowRotten: true,
    operation: 'fixed',
    difficulty: 'EXPERT',
    spawnDelay: 550,
    questions: [
      { question: 'Square → lines of symmetry = ?', answer: 4 },
      { question: 'Rectangle → lines of symmetry = ?', answer: 2 },
      { question: 'Equilateral triangle → lines of symmetry = ?', answer: 3 },
      { question: 'Regular pentagon → lines of symmetry = ?', answer: 5 },
    ],
  },
    ];
      export function getLevelConfig(level: number): LevelConfig {
      return levels.find((l) => l.id === level) || levels[levels.length - 1];
    }
    // NEW: Get level by category and level number
      export function getLevelByCategory(categoryId: string, levelInCategory: number): LevelConfig | undefined {
      return levels.find((l) => l.categoryId === categoryId && l.levelInCategory === levelInCategory);
    }
    // NEW: Get all levels in a category
    export function getLevelsByCategory(categoryId: string): LevelConfig[] {
    return levels.filter((l) => l.categoryId === categoryId);
  }

export default levels;